### ISSUE TITLE
Unable to add to Grafana

### ISSUE THREAD

**Issue by KOTIJim** [xperimental/netatmo-exporter#36]
Hello

I am trying to set up this exporter with Grafana, however when I try to add Prometheus as the data source I get the following errror:
"Error reading Prometheus: An error occurred within the plugin"
I am able to add other Prometheus data sources without issues.

netatmo-exporter v 1.5.0
Prometheus v 2.40.6
Grafana v 9.3

**Comment by xperimental** [comment]
Generally you do not need to add a separate Prometheus data source to Grafana for each exporter, so I'm not sure what you mean with "other Prometheus data sources" and how this relates to this exporter.

**Comment by xperimental** [comment]
Closed because there was no further information.
