### ISSUE TITLE
token.json overwritten with blank file after 3 hours

### ISSUE THREAD

**Issue by sbrooke** [xperimental/netatmo-exporter#37]
I figured this is a different problem so I would move it to a new issue.

Got the new-auth branch of 1.5.0 working once I changed the initial token.json to use "refresh_token" in the syntax. 

{"refresh_token":"123456}

After the first read of this file it updates with the auth token and expiry info, so it's writing to the file.

However, after 3 hours it overwrites the token.json with a blank file and fails. Probably has something to do with the expiry and not creating a new token file correctly when it has to refresh.

**Comment by sbrooke** [comment]
I had saved the token file with a different name just to have the refresh token handy. I copied that back to the regular token file, ran it again, and got two pulls before it wiped out the token file again. Could be that refresh token is expired, but then why would I get two pulls?

Anyway, just giving you more info about my experience.

**Comment by xperimental** [comment]
This issue should be fixed with the current state of the `new-auth` branch.
