### ISSUE TITLE
Port configuration

### ISSUE THREAD

**Issue by danny1605** [xperimental/netatmo-exporter#42]
Hello, I have the problem that the port is constantly changing itself. what settings do I have to make that the port is static ? thx

![Screenshot_20230112_090138](https://user-images.githubusercontent.com/59099140/212011591-ac356880-26db-4078-b935-83e30a6ca507.png)

**Comment by xperimental** [comment]
I think you need to have a look at [this section](https://docs.portainer.io/user/docker/containers/add#network-ports-configuration-section) of the portainer documentation.
