### ISSUE TITLE
Unable to start the exporter: Response: {"error":"unauthorized_client"}

### ISSUE THREAD

**Issue by giuliomagnifico** [xperimental/netatmo-exporter#44]
Hi, since few hours ago I got this error with my usual configuration:

`Response: {"error":"unauthorized_client"}`

Is something changed from Netatmo side or is only a temporary issue with their server?

thanks!

**Comment by xperimental** [comment]
It might still be a temporary issue, but it could also be that Netatmo finally removed the client authentication flow that was deprecated last year. See the other issue for more details.
