### ISSUE TITLE
trying to build for armv7 on rpi4

### ISSUE THREAD

**Issue by m-arx** [xperimental/netatmo-exporter#49]
I am trying to build netatmo-exporter for armv7 to run in docker on my Raspberry Pi 4 (no bragging).

I have no idea about go and little about programming in total.

yesterday it failed completely, after pulling this git again and updating go on the pi, it's failing with

"go: error loading module requirements
make: *** [Makefile:17: test] Error 1"

**Comment by xperimental** [comment]
Is that `armv7` as in 32bit ARM? If yes, why not go with arm64?

**Comment by m-arx** [comment]
Rasping is not yet 64 but as far as my research goes. I will try the 'make Image' soon. 

Danke.

**Comment by xperimental** [comment]
64bit builds of Raspbian ("Raspberry Pi OS") have been available for a while now. I have been running arm64 on both RPi3 and RPi4 for a while. Have a look here: https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit

If you're unsure what you're currently running, you can see the current kernel architecture using `uname`:

```shellsession
$ uname -a
Linux hostname 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by m-arx** [comment]
Right now my docker is stuck on this 

`Linux docker-pi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

But anyhow, the "make image" was successful.
