### ISSUE TITLE
Feature request: Netatmo Home Coach (aircare) support

### ISSUE THREAD

**Issue by neothematrix** [xperimental/netatmo-exporter#53]
hello!
first of all, great work!
I have an implementation request, I'm not very familiar with Go, but hopefully it shouldn't take too much time, is there any possibility that this exporter could take into consideration also the "Netatmo Home Coach" devices? They are very similar to the weather station and the API to call and the output are almost exactly the same (basically you need to call /gethomecoachsdata instead of /getstationsdata): https://dev.netatmo.com/apidocumentation/aircare
Maybe there could be a flag running netatmo-exporter to switch to home coach or some clever way to call both endpoints and merge the output into one?

I used to use this exporter: https://github.com/rolandsusans/netatmo-aircare-prometheus-exporter/ but unfortunately it hasn't been updated in a while and now the authentication is not working anymore.

I volunteer to test :-)

thanks!

**Comment by neothematrix** [comment]
sorry, it seems to be a duplicated of #43

**Comment by xperimental** [comment]
Hi @neothematrix . Thanks for the input. I already had another look at this a few weeks ago, but did not update the other issue so far. There are feature requests for other NetAtmo products as well. I can't give any guarantees, but I hope to get to some work done on hobby projects again soon :slightly_smiling_face: 

(I'm closing this as a duplicate, if this is ok)

**Comment by neothematrix** [comment]
sure I understand, thanks a lot for looking into it anyways!
BTW, I've managed somehow to modify your project to handle homecoach by taking some parts from rolandsusans project.

thanks!
