### ISSUE TITLE
Netatmo outage this morning

### ISSUE THREAD

**Issue by giuliomagnifico** [xperimental/netatmo-exporter#59]
Hi, sorry for the stupid title but I have no idea of what is going on since the 6:34AM, the exporter is working but I have no data since this morning. I really can't understand why. Any help where to investigate?

![CleanShot 2024-04-16 at 14 37 29@2x](https://github.com/xperimental/netatmo-exporter/assets/1975176/0d104e4e-baba-43e8-9dcf-d69d1cf8b3be)

```
root@Grafana:~# service netatmo-exporter status
● netatmo-exporter.service - netatmo-exporter
     Loaded: loaded (/etc/systemd/system/netatmo-exporter.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-04-16 14:19:02 CEST; 19min ago
   Main PID: 407 (netatmo-exporte)
      Tasks: 10 (limit: 4531)
        CPU: 577ms
     CGroup: /system.slice/netatmo-exporter.service
             └─407 /root/netatmo-exporter/netatmo-exporter -s xxx -i xxx --token-file token.json

Apr 16 14:19:02 Grafana systemd[1]: Started netatmo-exporter.
Apr 16 14:19:02 Grafana netatmo-exporter[407]: level=info msg="Loaded token from token.json."
Apr 16 14:19:02 Grafana netatmo-exporter[407]: level=info msg="Listen on :9210..."
```
Prometheus 

```
root@Grafana:~# service prometheus status
● prometheus.service - prometheus
     Loaded: loaded (/etc/systemd/system/prometheus.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/prometheus.service.d
             └─dietpi-process_tool.conf
     Active: active (running) since Tue 2024-04-16 14:19:02 CEST; 25min ago
   Main PID: 398 (prometheus)
      Tasks: 11 (limit: 4531)
        CPU: 1min 37.649s
     CGroup: /system.slice/prometheus.service
             └─398 /home/dietpi/prometheus/prometheus --config.file=/home/dietpi/prometheus/prometheus.yml --storage.tsdb.path=/home/dietpi/prometheus/data --storage.tsdb.retention.time=14d --storage.tsdb.retention.size=120GB --storage.tsdb.max-block-duration=30m --storage.tsdb.min-
block-duration=10m

Apr 16 14:25:04 Grafana prometheus[398]: ts=2024-04-16T12:25:04.631Z caller=compact.go:572 level=info component=tsdb msg="write block" mint=1713269400000 maxt=1713270000000 ulid=01HVKDWBDNH6XZJSBW4SAHR099 duration=449.071962ms
Apr 16 14:25:04 Grafana prometheus[398]: ts=2024-04-16T12:25:04.709Z caller=head.go:1338 level=info component=tsdb msg="Head GC completed" caller=truncateMemory duration=31.387055ms
Apr 16 14:25:04 Grafana prometheus[398]: ts=2024-04-16T12:25:04.711Z caller=checkpoint.go:101 level=info component=tsdb msg="Creating checkpoint" from_segment=797 to_segment=798 mint=1713270000000
Apr 16 14:25:04 Grafana prometheus[398]: ts=2024-04-16T12:25:04.845Z caller=head.go:1300 level=info component=tsdb msg="WAL checkpoint complete" first=797 last=798 duration=134.444314ms
Apr 16 14:25:05 Grafana prometheus[398]: ts=2024-04-16T12:25:05.739Z caller=compact.go:513 level=info component=tsdb msg="compact blocks" count=3 mint=1713267001918 maxt=1713268800000 ulid=01HVKDWC3FWRHVX2BN2M5Y3P5K sources="[01HVKBK1WTRQV1G5CE7NZ89NJQ 01HVKC5BW0W85R98EWGHVHMCMX 01H
VKCQNRN0EEM8Y7FDYK6JAC6]" duration=860.853926ms
Apr 16 14:25:05 Grafana prometheus[398]: ts=2024-04-16T12:25:05.829Z caller=db.go:1684 level=info component=tsdb msg="Deleting obsolete block" block=01HVKCQNRN0EEM8Y7FDYK6JAC6
Apr 16 14:25:05 Grafana prometheus[398]: ts=2024-04-16T12:25:05.841Z caller=db.go:1684 level=info component=tsdb msg="Deleting obsolete block" block=01HVKC5BW0W85R98EWGHVHMCMX
Apr 16 14:25:05 Grafana prometheus[398]: ts=2024-04-16T12:25:05.855Z caller=db.go:1684 level=info component=tsdb msg="Deleting obsolete block" block=01HVKBK1WTRQV1G5CE7NZ89NJQ
Apr 16 14:35:06 Grafana prometheus[398]: ts=2024-04-16T12:35:06.893Z caller=compact.go:572 level=info component=tsdb msg="write block" mint=1713270004127 maxt=1713270600000 ulid=01HVKEEQFS8VHDNNBFRW9T7SFT duration=531.795463ms
Apr 16 14:35:06 Grafana prometheus[398]: ts=2024-04-16T12:35:06.972Z caller=head.go:1338 level=info component=tsdb msg="Head GC completed" caller=truncateMemory duration=31.656648ms

```

My Netatmo app/token

![CleanShot 2024-04-16 at 14 45 23@2x](https://github.com/xperimental/netatmo-exporter/assets/1975176/7252f003-4de4-44ce-bac4-e480f7eb9aa2)

The Netatmo scrape endpoint on the DB

![CleanShot 2024-04-16 at 14 48 37@2x](https://github.com/xperimental/netatmo-exporter/assets/1975176/4ea32c5f-4b97-4448-8a02-7731cd531c24)

But looks like I have no more the queries from the exporter

![CleanShot 2024-04-16 at 14 47 01@2x](https://github.com/xperimental/netatmo-exporter/assets/1975176/9b69e7fe-7a6d-494e-9b89-4b43dcd7f46a)

I tried to reboot my Raspberry PI that I use as server for Grafana/Prometheus but is the same.

If I look at the website also looks like something is not working since the 8:45AM, but from the mobile app I can see the data.

![CleanShot 2024-04-16 at 14 51 37@2x](https://github.com/xperimental/netatmo-exporter/assets/1975176/58338544-3cf6-457d-aef1-e3719f7dbc64)

![Screenshot 2024-04-16 at 14 52 25](https://github.com/xperimental/netatmo-exporter/assets/1975176/05e94aa2-4a4a-4e0c-a9b5-e07f6b474f6c)

What is going on? It's my fault or something weird from the Netatmo server-side?

Thanks

**Comment by xperimental** [comment]
Hey @giuliomagnifico :wave: 

I noticed the same thing when I looked at my graphs today. The data stopped at ~6:50 UTC+2 and it recovered around 15:10 UTC+2. Unfortunately I was a bit too late, because I noticed it when it had already recovered, otherwise I could have had a look what the API returned.

As I also do not have any error messages, my guess would be that the API "forgot" all the sensors for a while, so it did not return an error but just returned an empty response (or something else that successfully parsed as JSON).

I think what we saw is an outage at NetAtmo. Did it also recover automatically for you?

**Comment by giuliomagnifico** [comment]
Hi, yes it’s back to working as usual. What a weird behavior, the API was returning nothing by the way, like you have no endpoints to scrape. 

This was my fear, that something went broken in my configuration for some reason, anyway I’m glad that is/was only an issue from Netatmo. 

Thanks for the feedback!

**Comment by xperimental** [comment]
Closing because it seems like this was an issue on NetAtmo's side and not an issue with the exporter. :sunny:
