### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by herver** [xperimental/netatmo-exporter#9]
Hello there,

I saw you updated the docker image with the recent changes you've made to the exporter.

Would it make sense to tag a new release on Github ? (maybe a minor release)

Thanks for the great work on the `netatmo_exporter` btw ! :+1:

**Comment by xperimental** [comment]
Hi @herver ,

I wanted to wait a while if my recent changes turned out to make it better or worse (see #8 ), but I have to admit that I forgot the last weeks.

Thanks for the reminder, the next release will come out shortly.

**Comment by xperimental** [comment]
Version 1.3.0 has just been released. :tada: 

Enjoy!
